a=int(input("Enter the temperature to convert celsius to Fahrenheit."))
d=int((a*9/5)+32)
print(a,".C is",d," in Fahrenheit")
b=int(input("Enter the temperature to convert Fahrenheit to celsius"))
d1=int((a-32)*5/9)
print(b,"F is",d1,"Celsius")